# Generated by Django 4.0.6 on 2022-11-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='faceModel',
        ),
    ]
